import { readFile, writeFile } from "node:fs/promises";

const recurrenceSource = (await readFile(new URL("recurrence.js", import.meta.url), "utf8"))
  .replace(/^export\s+/gm, "");
const appSource = (await readFile(new URL("app.js", import.meta.url), "utf8"))
  .replace(/^import\s*\{[\s\S]*?\}\s*from\s*["\']\.\/recurrence\.js["\'];\s*/m, "");

const bundle = `/* Generated by build.mjs. Edit recurrence.js or app.js instead. */\n(() => {\n${recurrenceSource}\n${appSource}\n})();\n`;
await writeFile(new URL("app.bundle.js", import.meta.url), bundle);

// Inline render-blocking assets so a slow secondary GitHub request cannot leave Safari on a blank page.
const [templateSource, stylesSource] = await Promise.all([
  readFile(new URL("index.template.html", import.meta.url), "utf8"),
  readFile(new URL("styles.css", import.meta.url), "utf8")
]);
const safeStyles = stylesSource.replace(/<\/style/gi, "<\\/style");
const safeBundle = bundle.replace(/<\/script/gi, "<\\/script");
const page = templateSource
  .replace(/  <link rel="stylesheet" href="styles\.css\?v=\d+">\r?\n/, `  <style data-build="inline">\n${safeStyles}\n  </style>\n`)
  .replace(/  <script defer src="app\.bundle\.js\?v=\d+"><\/script>/, `<script data-build="inline">\n${safeBundle}</script>`);
if (page === templateSource || !page.includes('data-build="inline"')) {
  throw new Error("index.template.html is missing the expected asset tags");
}
await writeFile(new URL("index.html", import.meta.url), page);
