import { readFile, writeFile } from "node:fs/promises";

const recurrenceSource = (await readFile(new URL("recurrence.js", import.meta.url), "utf8"))
  .replace(/^export\s+/gm, "");
const appSource = (await readFile(new URL("app.js", import.meta.url), "utf8"))
  .replace(/^import\s*\{[\s\S]*?\}\s*from\s*["']\.\/recurrence\.js["'];\s*/m, "");

const bundle = `/* Generated by build.mjs. Edit recurrence.js or app.js instead. */\n(() => {\n${recurrenceSource}\n${appSource}\n})();\n`;
await writeFile(new URL("app.bundle.js", import.meta.url), bundle);
